version: "3"

services:
  backend:
    build: .
    container_name: project_talker_manager
    tty: true
    stdin_open: true
    restart: always
    volumes:
      - ./src:/app/src
    ports:
      - 3001:3001
      - 9229:9229
    env_file:
      - .env

  db:
    container_name: project_talker_manager_db
    image: mysql:8.0.32
    restart: always
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD} # variável de ambiente do arquivo .env
      MYSQL_DATABASE: ${MYSQL_DATABASE_NAME} # variável de ambiente do arquivo .env
    volumes:
      - ./seed.sql:/docker-entrypoint-initdb.d/seed.sql

networks:
  default:
    name: talker_manager_net